version: "3.8"

services:
  # Backend Service
  backend:
    container_name: docker-backend
    ports:
      - "3000:3000"
    build:
      context: ./backend
      dockerfile: Dockerfile
  
  # Frontend Service
  frontend:
    container_name: docker-frontend
    ports:
      - "8080:8080"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend